[categoryName]
maps="Maps"
books="Books"
news="News"
[search]
related="Searches related to: <b>query</b>"
mayharm="This site may harm your computer."
sponsored_link="Sponsored Link"
sponsored_links="Sponsored Links"